import 'dart:convert';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:myday_ai/domain/entities/task_entity.dart';
import 'package:myday_ai/domain/entities/event_entity.dart';
import 'package:myday_ai/domain/entities/plan_entity.dart';
import 'package:myday_ai/data/repositories/task_repository.dart';
import 'package:myday_ai/data/repositories/event_repository.dart';
import 'package:myday_ai/data/repositories/plan_repository.dart';
import 'package:myday_ai/services/ai/gemini_service.dart';
import 'package:uuid/uuid.dart';

class IntentService {
  final GeminiService _geminiService;
  final TaskRepository _taskRepository;
  final EventRepository _eventRepository;
  final PlanRepository _planRepository;
  final Uuid _uuid = const Uuid();

  IntentService(
    this._geminiService,
    this._taskRepository,
    this._eventRepository,
    this._planRepository,
  );

  Future<Map<String, dynamic>> processUserMessage(String message) async {
    try {
      // Get AI intent analysis
      final intentData = await _geminiService.processMessage(message);
      final intent = intentData['intent'];

      // Execute the intent
      final result = await _executeIntent(intent, intentData);

      // Generate confirmation message
      final confirmation = _geminiService.generateConfirmationMessage(intentData);

      return {
        'success': true,
        'intent': intent,
        'result': result,
        'confirmation': confirmation,
        'rawIntent': intentData,
      };
    } catch (e) {
      return {
        'success': false,
        'error': e.toString(),
        'confirmation': '❌ Failed to process your request: $e',
      };
    }
  }

  Future<Map<String, dynamic>> _executeIntent(
    String intent,
    Map<String, dynamic> data,
  ) async {
    switch (intent) {
      case 'create_task':
        return await _createTask(data);
      case 'create_event':
        return await _createEvent(data);
      case 'create_plan':
        return await _createPlan(data);
      case 'list_tasks':
        return await _listTasks(data);
      case 'list_events':
        return await _listEvents(data);
      case 'update_task':
        return await _updateTask(data);
      case 'delete_task':
        return await _deleteTask(data);
      default:
        return {'status': 'unknown_intent', 'data': data};
    }
  }

  Future<Map<String, dynamic>> _createTask(Map<String, dynamic> data) async {
    final task = TaskEntity(
      id: 0, // Will be auto-generated by database
      title: data['title'],
      description: data['description'],
      dueDate: DateTime.parse(data['dueDate']),
      priority: TaskPriority.values.firstWhere(
        (p) => p.name == data['priority'],
        orElse: () => TaskPriority.medium,
      ),
      isCompleted: false,
      createdAt: DateTime.now(),
      planId: data['planId'],
    );

    final id = await _taskRepository.createTask(task);
    return {'taskId': id, 'task': task};
  }

  Future<Map<String, dynamic>> _createEvent(Map<String, dynamic> data) async {
    final event = EventEntity(
      id: 0,
      title: data['title'],
      description: data['description'],
      startTime: DateTime.parse(data['startTime']),
      endTime: DateTime.parse(data['endTime']),
      isAllDay: data['isAllDay'] ?? false,
      createdAt: DateTime.now(),
      planId: data['planId'],
    );

    final id = await _eventRepository.createEvent(event);
    return {'eventId': id, 'event': event};
  }

  Future<Map<String, dynamic>> _createPlan(Map<String, dynamic> data) async {
    final planId = _uuid.v4();
    final tasks = data['tasks'] as List? ?? [];
    final events = data['events'] as List? ?? [];

    final taskIds = <String>[];
    for (final taskData in tasks) {
      taskData['planId'] = planId;
      final result = await _createTask(taskData);
      taskIds.add(result['taskId'].toString());
    }

    final eventIds = <String>[];
    for (final eventData in events) {
      eventData['planId'] = planId;
      final result = await _createEvent(eventData);
      eventIds.add(result['eventId'].toString());
    }

    final plan = PlanEntity(
      id: 0,
      title: data['title'],
      description: data['description'],
      createdAt: DateTime.now(),
      taskIds: taskIds,
      eventIds: eventIds,
    );

    final id = await _planRepository.createPlan(plan);
    return {'planId': id, 'plan': plan};
  }

  Future<Map<String, dynamic>> _listTasks(Map<String, dynamic> data) async {
    final filter = data['filter'] ?? 'all';
    final tasks = await _taskRepository.getTasks(filter: filter);
    return {'tasks': tasks};
  }

  Future<Map<String, dynamic>> _listEvents(Map<String, dynamic> data) async {
    final filter = data['filter'] ?? 'all';
    final events = await _eventRepository.getEvents(filter: filter);
    return {'events': events};
  }

  Future<Map<String, dynamic>> _updateTask(Map<String, dynamic> data) async {
    // Implementation depends on your UI for selecting tasks
    // For now, return success
    return {'status': 'update_not_implemented'};
  }

  Future<Map<String, dynamic>> _deleteTask(Map<String, dynamic> data) async {
    // Implementation depends on your UI for selecting tasks
    // For now, return success
    return {'status': 'delete_not_implemented'};
  }
}

final intentServiceProvider = Provider<IntentService>((ref) {
  final geminiService = ref.watch(geminiServiceProvider);
  final taskRepo = ref.watch(taskRepositoryProvider);
  final eventRepo = ref.watch(eventRepositoryProvider);
  final planRepo = ref.watch(planRepositoryProvider);
  return IntentService(geminiService, taskRepo, eventRepo, planRepo);
});